[2022-10-14 20:35:57,850] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: generate_data.export_tables_to_dir scheduled__2022-10-14T20:30:40.208472+00:00 [queued]>
[2022-10-14 20:35:57,882] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: generate_data.export_tables_to_dir scheduled__2022-10-14T20:30:40.208472+00:00 [queued]>
[2022-10-14 20:35:57,883] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-14 20:35:57,885] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-10-14 20:35:57,885] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-14 20:35:57,934] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): export_tables_to_dir> on 2022-10-14 20:30:40.208472+00:00
[2022-10-14 20:35:57,962] {standard_task_runner.py:52} INFO - Started process 4633 to run task
[2022-10-14 20:35:57,988] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'generate_data', 'export_tables_to_dir', 'scheduled__2022-10-14T20:30:40.208472+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/generate_data.py', '--cfg-path', '/tmp/tmpvfpw3msv', '--error-file', '/tmp/tmppaetgiqg']
[2022-10-14 20:35:57,991] {standard_task_runner.py:80} INFO - Job 109: Subtask export_tables_to_dir
[2022-10-14 20:35:58,253] {task_command.py:371} INFO - Running <TaskInstance: generate_data.export_tables_to_dir scheduled__2022-10-14T20:30:40.208472+00:00 [running]> on host 614e96fbdf07
[2022-10-14 20:35:58,702] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=generate_data
AIRFLOW_CTX_TASK_ID=export_tables_to_dir
AIRFLOW_CTX_EXECUTION_DATE=2022-10-14T20:30:40.208472+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-14T20:30:40.208472+00:00
[2022-10-14 20:35:58,734] {export_tables.py:37} INFO - Connection to database success
[2022-10-14 20:35:58,777] {export_tables.py:120} INFO - Working on transaction
[2022-10-14 20:35:58,795] {export_tables.py:86} INFO - Exporting 505 rows into csv.
[2022-10-14 20:35:58,799] {export_tables.py:96} CRITICAL - Something went wrong at exporting the table to container storage
[2022-10-14 20:35:58,818] {export_tables.py:120} INFO - Working on customer
[2022-10-14 20:35:58,822] {export_tables.py:86} INFO - Exporting 505 rows into csv.
[2022-10-14 20:35:58,830] {export_tables.py:96} CRITICAL - Something went wrong at exporting the table to container storage
[2022-10-14 20:35:58,837] {export_tables.py:106} INFO - Both cursor and conn closed successfully
[2022-10-14 20:35:58,840] {export_tables.py:127} INFO - Both thables export successfully
[2022-10-14 20:35:58,844] {python.py:173} INFO - Done. Returned value was: None
[2022-10-14 20:35:58,953] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=generate_data, task_id=export_tables_to_dir, execution_date=20221014T203040, start_date=20221014T203557, end_date=20221014T203558
[2022-10-14 20:35:59,035] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-14 20:35:59,423] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
