[2022-10-17 18:07:11,173] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: generate_data.export_tables_to_dir manual__2022-10-17T18:06:04.345588+00:00 [queued]>
[2022-10-17 18:07:11,189] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: generate_data.export_tables_to_dir manual__2022-10-17T18:06:04.345588+00:00 [queued]>
[2022-10-17 18:07:11,190] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 18:07:11,190] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-10-17 18:07:11,191] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-17 18:07:11,209] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): export_tables_to_dir> on 2022-10-17 18:06:04.345588+00:00
[2022-10-17 18:07:11,218] {standard_task_runner.py:52} INFO - Started process 48501 to run task
[2022-10-17 18:07:11,223] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'generate_data', 'export_tables_to_dir', 'manual__2022-10-17T18:06:04.345588+00:00', '--job-id', '432', '--raw', '--subdir', 'DAGS_FOLDER/generate_data.py', '--cfg-path', '/tmp/tmpk2npo2qr', '--error-file', '/tmp/tmpkl3b_jg0']
[2022-10-17 18:07:11,225] {standard_task_runner.py:80} INFO - Job 432: Subtask export_tables_to_dir
[2022-10-17 18:07:11,312] {task_command.py:371} INFO - Running <TaskInstance: generate_data.export_tables_to_dir manual__2022-10-17T18:06:04.345588+00:00 [running]> on host 614e96fbdf07
[2022-10-17 18:07:11,407] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=generate_data
AIRFLOW_CTX_TASK_ID=export_tables_to_dir
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T18:06:04.345588+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-17T18:06:04.345588+00:00
[2022-10-17 18:07:11,419] {export_tables.py:37} INFO - Connection to database success
[2022-10-17 18:07:11,421] {export_tables.py:130} INFO - Working on transaction
[2022-10-17 18:07:11,428] {export_tables.py:94} INFO - Exporting 2801 rows into csv.
[2022-10-17 18:07:11,441] {export_tables.py:104} CRITICAL - <class 'psycopg2.errors.UndefinedFile'>
[2022-10-17 18:07:11,442] {export_tables.py:105} CRITICAL - could not open file "/opt/transaction/2022-10-17/transaction_2022-10-17.csv" for writing: No such file or directory
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.

[2022-10-17 18:07:11,443] {export_tables.py:106} CRITICAL - Something went wrong at exporting the table to container storage
[2022-10-17 18:07:11,443] {export_tables.py:130} INFO - Working on customer
[2022-10-17 18:07:11,445] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/export_tables.py", line 131, in export
    copy_table(cursor=connection_cursor, conn=connection, path=f'/opt/{table.get(_)}', table=table.get(_), days=days)
  File "/opt/airflow/dags/export_tables.py", line 93, in copy_table
    rows = count_rows(cursor, table=table)
  File "/opt/airflow/dags/export_tables.py", line 49, in count_rows
    cursor.execute(f'SELECT * FROM {table}')
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2022-10-17 18:07:11,457] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=generate_data, task_id=export_tables_to_dir, execution_date=20221017T180604, start_date=20221017T180711, end_date=20221017T180711
[2022-10-17 18:07:11,470] {standard_task_runner.py:97} ERROR - Failed to execute job 432 for task export_tables_to_dir (current transaction is aborted, commands ignored until end of transaction block
; 48501)
[2022-10-17 18:07:11,518] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-17 18:07:11,565] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
