[2022-10-24T21:17:05.298+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: unify_transform_enrich_data.load_and_enrich_unified_data manual__2022-10-24T20:56:39.188880+00:00 [failed]>
[2022-10-24T21:17:05.359+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: unify_transform_enrich_data.load_and_enrich_unified_data manual__2022-10-24T20:56:39.188880+00:00 [failed]>
[2022-10-24T21:17:05.362+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-24T21:17:05.364+0000] {taskinstance.py:1363} INFO - Starting attempt 5 of 2
[2022-10-24T21:17:05.369+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-24T21:17:05.408+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): load_and_enrich_unified_data> on 2022-10-24 20:56:39.188880+00:00
[2022-10-24T21:17:05.440+0000] {standard_task_runner.py:54} INFO - Started process 62950 to run task
[2022-10-24T21:17:05.449+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'unify_transform_enrich_data', 'load_and_enrich_unified_data', 'manual__2022-10-24T20:56:39.188880+00:00', '--job-id', '567', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_and_unify_datasets.py', '--cfg-path', '/tmp/tmpo6qc12yo']
[2022-10-24T21:17:05.463+0000] {standard_task_runner.py:83} INFO - Job 567: Subtask load_and_enrich_unified_data
[2022-10-24T21:17:05.469+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/load_and_unify_datasets.py
[2022-10-24T21:17:05.938+0000] {task_command.py:384} INFO - Running <TaskInstance: unify_transform_enrich_data.load_and_enrich_unified_data manual__2022-10-24T20:56:39.188880+00:00 [running]> on host c94e224fed05
[2022-10-24T21:17:06.523+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=unify_transform_enrich_data
AIRFLOW_CTX_TASK_ID=load_and_enrich_unified_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-24T20:56:39.188880+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-24T20:56:39.188880+00:00
[2022-10-24T21:17:45.859+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pyspark_scripts.py", line 239, in load_and_enrich_data
    unified_model = dump_df.select('id', 'customer_id', 'store_id', 'tt_type', 'float_amount', 'customer_first_name', 'customer_last_name', 'phone_number', 'address', 'timestamp')
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/dataframe.py", line 2023, in select
    jdf = self._jdf.select(self._jcols(*cols))
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 196, in deco
    raise converted from None
pyspark.sql.utils.AnalysisException: Column 'float_amount' does not exist. Did you mean one of the following? [amount, phone_number, store_id, t_type, timestamp, tt_type, address, customer_id, type, id, customer_last_name, customer_first_name];
'Project [id#0L, customer_id#1, store_id#2L, tt_type#33, 'float_amount, customer_first_name#5, customer_last_name#6, phone_number#7, address#8, timestamp#9]
+- Project [id#0L, customer_id#1, store_id#2L, type#3L, amount#4, customer_first_name#5, customer_last_name#6, phone_number#7, address#8, timestamp#9, t_type#20, CASE WHEN (t_type#20 >= 0.5) THEN 1 ELSE 0 END AS tt_type#33]
   +- Project [id#0L, customer_id#1, store_id#2L, type#3L, amount#4, customer_first_name#5, customer_last_name#6, phone_number#7, address#8, timestamp#9, CASE WHEN isnull(type#3L) THEN rand(1892169748139866570) ELSE cast(type#3L as double) END AS t_type#20]
      +- Relation [id#0L,customer_id#1,store_id#2L,type#3L,amount#4,customer_first_name#5,customer_last_name#6,phone_number#7,address#8,timestamp#9] parquet

[2022-10-24T21:17:45.892+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=unify_transform_enrich_data, task_id=load_and_enrich_unified_data, execution_date=20221024T205639, start_date=20221024T211705, end_date=20221024T211745
[2022-10-24T21:17:45.925+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 567 for task load_and_enrich_unified_data (Column 'float_amount' does not exist. Did you mean one of the following? [amount, phone_number, store_id, t_type, timestamp, tt_type, address, customer_id, type, id, customer_last_name, customer_first_name];
'Project [id#0L, customer_id#1, store_id#2L, tt_type#33, 'float_amount, customer_first_name#5, customer_last_name#6, phone_number#7, address#8, timestamp#9]
+- Project [id#0L, customer_id#1, store_id#2L, type#3L, amount#4, customer_first_name#5, customer_last_name#6, phone_number#7, address#8, timestamp#9, t_type#20, CASE WHEN (t_type#20 >= 0.5) THEN 1 ELSE 0 END AS tt_type#33]
   +- Project [id#0L, customer_id#1, store_id#2L, type#3L, amount#4, customer_first_name#5, customer_last_name#6, phone_number#7, address#8, timestamp#9, CASE WHEN isnull(type#3L) THEN rand(1892169748139866570) ELSE cast(type#3L as double) END AS t_type#20]
      +- Relation [id#0L,customer_id#1,store_id#2L,type#3L,amount#4,customer_first_name#5,customer_last_name#6,phone_number#7,address#8,timestamp#9] parquet
; 62950)
[2022-10-24T21:17:46.017+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-24T21:17:46.065+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
