[2022-10-21 14:39:00,596] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: pyspark_jobs.load_and_normalize_rdbms_data manual__2022-10-21T14:38:50.753124+00:00 [queued]>
[2022-10-21 14:39:00,613] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: pyspark_jobs.load_and_normalize_rdbms_data manual__2022-10-21T14:38:50.753124+00:00 [queued]>
[2022-10-21 14:39:00,614] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-21 14:39:00,614] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-10-21 14:39:00,615] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-21 14:39:00,638] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_and_normalize_rdbms_data> on 2022-10-21 14:38:50.753124+00:00
[2022-10-21 14:39:00,649] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-10-21 14:39:00,649] {standard_task_runner.py:52} INFO - Started process 11053 to run task
[2022-10-21 14:39:00,657] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'pyspark_jobs', 'load_and_normalize_rdbms_data', 'manual__2022-10-21T14:38:50.753124+00:00', '--job-id', '468', '--raw', '--subdir', 'DAGS_FOLDER/pyspark_jobs.py', '--cfg-path', '/tmp/tmplaqlh7uh', '--error-file', '/tmp/tmpmao5g8d8']
[2022-10-21 14:39:00,658] {standard_task_runner.py:80} INFO - Job 468: Subtask load_and_normalize_rdbms_data
[2022-10-21 14:39:00,812] {task_command.py:371} INFO - Running <TaskInstance: pyspark_jobs.load_and_normalize_rdbms_data manual__2022-10-21T14:38:50.753124+00:00 [running]> on host ee1a3e6935ec
[2022-10-21 14:39:00,817] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-10-21 14:39:00,822] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-10-21 14:39:00,825] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 507, in send_command
    "Error while sending", e, proto.ERROR_ON_SEND)
py4j.protocol.Py4JNetworkError: Error while sending
[2022-10-21 14:39:00,841] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-10-21 14:39:00,937] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pyspark_jobs
AIRFLOW_CTX_TASK_ID=load_and_normalize_rdbms_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-21T14:38:50.753124+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-21T14:38:50.753124+00:00
[2022-10-21 14:39:00,939] {python.py:173} INFO - Done. Returned value was: None
[2022-10-21 14:39:00,960] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=pyspark_jobs, task_id=load_and_normalize_rdbms_data, execution_date=20221021T143850, start_date=20221021T143900, end_date=20221021T143900
[2022-10-21 14:39:01,003] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-21 14:39:01,057] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
